apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portfolio
  annotations:
    github.com/project-slug: SatyaAchanta/portfolio
    backstage.io/techdocs-ref: value
  tags:
    - website
    - portfolio
  links:
    - url: https://www.itsmesatya.info
      title: Website
spec:
  type: website
  lifecycle: production
  owner: guests
